# This is a basic workflow to help you get started with Actions

name: DevDailyCard

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *"


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.1.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
